# Generated by Django 3.1.7 on 2021-04-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(),
        ),
    ]
