# Generated by Django 3.1.7 on 2021-04-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210414_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
